apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-k8s.fullname" . }}
  labels:
    app: {{ include "demo-k8s.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "demo-k8s.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "demo-k8s.name" . }}
    spec:
      containers:
        - name: demo-k8s
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.containerPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.containerPort }}
